[package]
name = "xsission-ast-parser"
version = "0.1.1"
edition = "2021"
description = "Rust-based AST parser for the Function Dependency Visualizer"
authors = ["Xsission Labs"]
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
swc_common = { version = "0.31.12", features = ["tty-emitter"] }
swc_ecma_ast = "0.106.2"
swc_ecma_parser = "0.133.0"
swc_ecma_visit = "0.92.2"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["console"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1 